### PR TITLE
compatibility with Karaf 4

### PR DESCRIPTION
**Pull request by jdr0887**
Mostly just updating dependency versions.  There were a few compile time errors due to Wicket version (IApplicationSettings -> ApplicationSettings, etc.)

### CODE REVIEW

**Comment by ANierbeck** [comment]
Hi could you please open a corresponding Jira issue for this?
https://ops4j1.jira.com/projects/PAXWICKET/summary

thanks, Achim

**Comment by laeubi** [comment]
Is there any reason in removing the dependecy version and pushing up version ranges? If there is no need (e.g. API changes that affect pax wicket) we shoudl support a range as wide as possible to make it possible to use the bundle in as much enviourments as possible without any problems.

**Comment by jdr0887** [comment]
I don't disagree...I was overzealous in my edits.  I will try to remedy
that today.

On Wed, Jan 20, 2016 at 2:25 AM, laeubi <notifications@github.com> wrote:

> Is there any reason in removing the dependecy version and pushing up
> version ranges? If there is no need (e.g. API changes that affect pax
> wicket) we shoudl support a range as wide as possible to make it possible
> to use the bundle in as much enviourments as possible without any problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.wicket/pull/20#issuecomment-173117102>
> .
>



-- 
Jason Reilly

**Comment by nmwael** [comment]
Hmm are somebody else working on this?

I am in the midst of upgrading to latest karaf(4.0.4) and wicket 6. + other
interdependencies

On Wed, Jan 20, 2016 at 1:48 PM, Jason Reilly <notifications@github.com>
wrote:

> I don't disagree...I was overzealous in my edits. I will try to remedy
> that today.
>
> On Wed, Jan 20, 2016 at 2:25 AM, laeubi <notifications@github.com> wrote:
>
> > Is there any reason in removing the dependecy version and pushing up
> > version ranges? If there is no need (e.g. API changes that affect pax
> > wicket) we shoudl support a range as wide as possible to make it possible
> > to use the bundle in as much enviourments as possible without any
> problems.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ops4j/org.ops4j.pax.wicket/pull/20#issuecomment-173117102
> >
> > .
> >
>
>
>
> --
> Jason Reilly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.wicket/pull/20#issuecomment-173194701>
> .
>



-- 
Best regards / Med venlig hilsen
Nino Martinez

**Comment by jdr0887** [comment]
Not to my knowledge.

On Wed, Jan 20, 2016 at 7:53 AM, nmwael <notifications@github.com> wrote:

> Hmm are somebody else working on this?
>
> I am in the midst of upgrading to latest karaf(4.0.4) and wicket 6. + other
> interdependencies
>
> On Wed, Jan 20, 2016 at 1:48 PM, Jason Reilly <notifications@github.com>
> wrote:
>
> > I don't disagree...I was overzealous in my edits. I will try to remedy
> > that today.
> >
> > On Wed, Jan 20, 2016 at 2:25 AM, laeubi <notifications@github.com>
> wrote:
> >
> > > Is there any reason in removing the dependecy version and pushing up
> > > version ranges? If there is no need (e.g. API changes that affect pax
> > > wicket) we shoudl support a range as wide as possible to make it
> possible
> > > to use the bundle in as much enviourments as possible without any
> > problems.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/ops4j/org.ops4j.pax.wicket/pull/20#issuecomment-173117102
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Jason Reilly
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/ops4j/org.ops4j.pax.wicket/pull/20#issuecomment-173194701
> >
> > .
> >
>
>
>
> --
> Best regards / Med venlig hilsen
> Nino Martinez
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.wicket/pull/20#issuecomment-173195489>
> .
>



-- 
Jason Reilly

**Comment by pablogomezp** [comment]
good to see sombody is working on this. I've just opened today a ticket
https://ops4j1.jira.com/browse/PAXWICKET-476

**Comment by ANierbeck** [comment]
to accept this pull request, the issues above need to be addressed, actually it would be best to squash these commits to one, and reference the jira issue.

**Pull request closed without merging**
